<a href="https://colab.research.google.com/github/bhargav23/JNTU_PYTHON_Assignments/blob/master/Numpy_exercises_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment questions for Numpy

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.18.5


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)

#### 4. How to find the size of any array (★☆☆)

In [4]:
x.size

10

#### 5. Create a null vector of size 10(★☆☆)

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix (★☆☆)

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Create a 3x3x3 array with random values (★☆☆)

In [9]:
np.random.randint(27,size=(3,3,3))

array([[[ 1,  8,  2],
        [ 5,  3, 24],
        [11, 25,  1]],

       [[ 4,  3, 21],
        [ 6, 24, 20],
        [23,  7,  7]],

       [[ 6,  0, 15],
        [ 0, 17,  2],
        [16, 14,  7]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
x = np.random.randint(1000,size=(10,10))
print("Minimum = ",x.min())
print("Maximum = ",x.max())

Minimum =  25
Maximum =  988


#### 11. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
x = np.random.randint(1000,size=30)
print("Mean = ",x.mean())

Mean =  527.0666666666667


#### 12. Create a 2d array (★☆☆)

In [12]:
x = np.array([4,2,5,1]).reshape(2,2)
x

array([[4, 2],
       [5, 1]])

#### 13. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
a = np.matrix(np.random.randint(100,size=(5,3)))
b = np.matrix(np.random.randint(6,size=(3,2)))
np.dot(a,b)

matrix([[418, 356],
        [760, 205],
        [984, 456],
        [582,  28],
        [475,  54]])

#### 14. Create a 5X5 array with random values and compute statistics such as mean,med,std and var

In [14]:
x = np.random.randint(100,size=(5,5))
print("Mean = ",x.mean())
print("Std = ",x.std())
print("Var = ",x.var())

Mean =  34.36
Std =  24.051411600985087
Var =  578.4704


#### 15. Convert below statement to lowercase and first letter to upper case

"Am I learning new from these python sessions ?"

In [15]:
s = np.array("Am I learning new from these python sessions ?")
print(np.char.title(s))

Am I Learning New From These Python Sessions ?


#### 16. Convert your response (for above question)  to upper case

In [16]:
s = np.array("Am I learning new from these python sessions ?")
print(np.char.lower(s))

am i learning new from these python sessions ?


#### 17. Create 4X4 array and combine another 2X4 array vertically

In [20]:
x = np.random.randint(100,size=(4,4))
y = np.random.randint(100,size=(2,4))
print(x)
print(y)
np.append(x,y,axis=0)

[[65 23 67 64]
 [20 94 71 97]
 [37 56 35 88]
 [44 93 84 20]]
[[57 38 30 48]
 [90 92 61 81]]


array([[65, 23, 67, 64],
       [20, 94, 71, 97],
       [37, 56, 35, 88],
       [44, 93, 84, 20],
       [57, 38, 30, 48],
       [90, 92, 61, 81]])